---
title: "LeafTraits"
author: "Marcela Morassi"
date: "8/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Marcela's startup (wd, data, packages)
```{r}
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(rcompanion)
library(ggdark)

setwd("C:/Users/Marcela Morassi/Dropbox/2021_SummerInterns/MM")

data <- read.csv("LeafTraitsTW0.csv")

traits <- read.csv("SERCmasterdata2021CSV.csv")

```

Amy's startup
```{r}
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(rcompanion)
library(ggdark)

setwd("C:/Users/hrusk/Dropbox (Smithsonian)/2021_SummerInterns/MM")

data <- read.csv("LeafTraitsTW0.csv")

traits <- read.csv("SERCmasterdata2021CSV.csv")

```

Data manipulation
```{r}

##filter for samples with percent damage##
percent_damage <- data %>% 
  filter(percent_damage>0)

##removing outlier/false thickness measurements##
############ Marcela will fix these #############

traits2 <- traits %>% 
  filter(thickness<.3)

##data preparation for ordinations##

traits3 <- traits2 %>%
  unite(site.species, c("site", "species"))

ord_data1 <- traits3 %>%
  select(site.species, toughness, thickness, water_content_percent)


```


BarStats Function 
```{r}
#barGraphStats(data=, variable="", byFactorNames=c(""))
barGraphStats <- function(data, variable, byFactorNames) {
  count <- length(byFactorNames)
  N <- aggregate(data[[variable]], data[byFactorNames], FUN=length)
  names(N)[1:count] <- byFactorNames
  names(N) <- sub("^x$", "N", names(N))
  mean <- aggregate(data[[variable]], data[byFactorNames], FUN=mean)
  names(mean)[1:count] <- byFactorNames
  names(mean) <- sub("^x$", "mean", names(mean))
  sd <- aggregate(data[[variable]], data[byFactorNames], FUN=sd)
  names(sd)[1:count] <- byFactorNames
  names(sd) <- sub("^x$", "sd", names(sd))
  preSummaryStats <- merge(N, mean, by=byFactorNames)
  finalSummaryStats <- merge(preSummaryStats, sd, by=byFactorNames)
  finalSummaryStats$se <- finalSummaryStats$sd / sqrt(finalSummaryStats$N)
  return(finalSummaryStats)
}

```


Damage by species
```{r}
##Creating colourblind palette###
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

##saved graph as variable to edit theme below##
g1 <- ggplot(data = barGraphStats(data = percent_damage, variable = "percent_damage", byFactorNames = c("species")), aes(x=species, y=mean, fill = species)) +
    geom_bar(stat='identity', position=position_dodge()) +
    geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width = 0.2, position = position_dodge(0.9)) +
    xlab("Species") + ylab("Percent Damage") +
    scale_fill_manual(values = cbPalette) 

##setting theme to remove background grid and add axis lines##    
g1 + theme(panel.background = element_rect(fill = "black"), plot.background = element_rect(fill = "black"), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "white"), axis.text = element_text(size = 10, colour = "white", face = "italic"), axis.title.y = element_text(size = 16, margin = margin(t = 0, r = 10, b = 0, l = 0), colour = "white"), axis.title.x = element_text(size = 16, margin = margin(t = 10, r = 0, b = 0, l = 0), colour = "white"), legend.position = "none")

ggsave("damage_v_species.png")

```

Boxplot percent damage by species
```{r}
ggplot(percent_damage, aes(x=species, y=percent_damage)) + geom_boxplot()

```

Trait boxplots
```{r}
g2 <- ggplot(traits, aes(x=species, y=toughness, fill = site)) + geom_boxplot() +
  xlab("Species") +ylab("Toughness")
 
g2 + theme(panel.background = element_rect(fill = "black"), plot.background = element_rect(fill = "black"), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "white"), axis.text = element_text(size = 9, colour = "white", face = "italic"), axis.title.y = element_text(size = 16, margin = margin(t = 0, r = 10, b = 0, l = 0), colour = "white"), axis.title.x = element_text(size = 16, margin = margin(t = 10, r = 0, b = 0, l = 0), colour = "white"), legend.background = element_blank(), legend.key = element_rect( fill = "black"), legend.text = element_text(colour = "white"))

ggsave("toughness_site_species.png")

g3 <- ggplot(traits2, aes(x=species, y=thickness, fill = site)) + geom_boxplot()+
  xlab("Species") + ylab ("Thickness")

g3 + theme(panel.background = element_rect(fill = "black"), plot.background = element_rect(fill = "black"), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "white"), axis.text = element_text(size = 9, colour = "white", face = "italic"), axis.title.y = element_text(size = 16, margin = margin(t = 0, r = 10, b = 0, l = 0), colour = "white"), axis.title.x = element_text(size = 16, margin = margin(t = 10, r = 0, b = 0, l = 0), colour = "white"), legend.background = element_blank(), legend.key = element_rect( fill = "black"), legend.text = element_text(colour = "white"))

ggsave("thickness_species_site.png")

g4 <- ggplot(traits2, aes(x=species, y=water_content_percent, fill=site)) + geom_boxplot()+
  xlab("Species") + ylab("Water Content Percent")

g4 + theme(panel.background = element_rect(fill = "black"), plot.background = element_rect(fill = "black"), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "white"), axis.text = element_text(size = 9, colour = "white", face = "italic"), axis.title.y = element_text(size = 16, margin = margin(t = 0, r = 10, b = 0, l = 0), colour = "white"), axis.title.x = element_text(size = 16, margin = margin(t = 10, r = 0, b = 0, l = 0), colour = "white"), legend.background = element_blank(), legend.key = element_rect( fill = "black"), legend.text = element_text(colour = "white"))

ggsave("water_species_site.png")


```

normality testing of traits
```{r}
shapiro.test(traits2$water_content_percent)


#visualizing distribution
plot(traits2$water_content_percent)
hist(traits2$water_content_percent)
```

Load in new packages
```{r}
library(lme4)
library(nlme)
library(lattice)
library(effects)
library(MuMIn)
```

models
```{r}
mod0 <- lm(water_content_percent ~ species, data = traits2)

mod1 <- lm(water_content_percent ~ species*site, data = traits2)

mod2 <- lme(water_content_percent ~ species*site, random= ~1|TreeID, data = traits2)

mod3 <- lme(toughness ~ species*site, random= ~1|TreeID, data = traits2)

mod4 <- lme(thickness ~ species*site, random= ~1|TreeID, data = traits2)

mod5 <- lme(percent_damage ~ species, random= ~1|TreeID, data = percent_damage)

mod6 <- lm(percent_damage ~species, data = percent_damage)

mod7 <- lme(percent_damage ~ toughness, random= ~1|TreeID, data = percent_damage)

mod8 <- lme(percent_damage ~ thickness, random= ~1|TreeID, data = percent_damage)

mod9 <- lme(percent_damage ~ water_content_percent, random= ~1|TreeID, data = percent_damage)

mod10 <- lme(percent_damage ~ SLA, random= ~1|TreeID, data = percent_damage)
```

ordinations
```{r}

library(vegan)

##principal coordinates analysis##

ord1<- metaMDS(ord_data1[,2:4])

pcoa <- capscale(ord_data1[, 2:4] ~ 1, dist = "bray" )

pcoa2 <- capscale(ord_data1[, 2:4] ~ site.species, data = traits3, dist = "bray" )

#plot(pcoa) 
#points(pcoa, display = "sites", col = 'grey') 
#text(pcoa, display = 'bp', col = 'blue')



#plots <- 1:nrow(ord1)
#plotData <- ord_data1[,1]
#plot(sppBC$points,col=as.factor(plotData$location))
#ordiellipse(sppBC, groups = as.factor(plotData$Watershed), kind = "sd", display = "plots", label = T)


```

regression for traits
```{r}
ggplot(percent_damage, aes(x = water_content_percent, y = percent_damage, color = species)) + 
  geom_point(shape = 1) +
  dark_theme_classic()+
  theme(legend.position = c(0.85,0.81))+
  scale_colour_hue(l=50) +
  xlab("Water Content Percent") + ylab("Percent Damage")
  
g5 <- ggplot(percent_damage, aes(x = water_content_percent, y = percent_damage, color = species)) + 
  geom_point(shape = 20, size = 4) +
  geom_smooth(method = "lm", se = F)
  xlab("Percent Water Content") + ylab("Percent Damage")

g5 + theme(panel.background = element_rect(fill = "black"), plot.background = element_rect(fill = "black"), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "white"), axis.text = element_text(size = 9, colour = "white", face = "italic"), axis.title.y = element_text(size = 16, margin = margin(t = 0, r = 10, b = 0, l = 0), colour = "white"), axis.title.x = element_text(size = 16, margin = margin(t = 10, r = 0, b = 0, l = 0), colour = "white"), legend.background = element_blank(), legend.key = element_rect( fill = "black"), legend.text = element_text(colour = "white"))
  
ggsave("percentdamage_watercontent.png") 
  
  #dark_theme_bw()+
  #theme(legend.position = "top")+
  #scale_colour_hue(l=50) +
  #facet_grid(species ~ .)
  #xlab("Water Content Percent") + ylab("Percent Damage")

ggplot(percent_damage, aes(x = SLA, y = percent_damage, color = species)) + 
  geom_point(shape = 1) +
  scale_colour_hue(l=50) +
  geom_smooth(method = lm, se = FALSE, fullrange = TRUE) +
  xlab("SLA") + ylab("Percent Damage")

ggsave("WCplot.png")
```














